package com.markdownreader.markdown;

import com.markdownreader.ui.Theme;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;

/**
 * Wraps the HTML fragment generated by {@link MarkdownRenderer} into a
 * complete, styled HTML document ready for the {@code WebView}.
 *
 * <p>Everything is inlined from resources bundled in the application, so
 * rendering works <strong>100% offline</strong>: the theme CSS (light/dark),
 * code syntax highlighting via highlight.js (script + theme), and emojis
 * converted to colored SVG images (twemoji) by {@link EmojiImageRenderer}.
 *
 * <p>highlight.js is bundled instead of loaded from a CDN because the JavaFX
 * WebView may be offline; emojis are converted on the Java side because the
 * embedded WebKit does not render colored emoji fonts and does not match
 * astral-plane emojis via JS.
 */
public final class HtmlPageBuilder {

    // highlight.js v11.9.0 — script e temas empacotados em /web/hljs/.

    private final String baseCss;
    private final String hljsJs;
    private final String hlThemeLight;
    private final String hlThemeDark;
    private final EmojiImageRenderer emojiRenderer = new EmojiImageRenderer();

    public HtmlPageBuilder() {
        this.baseCss = readResource("/web/markdown.css");
        this.hljsJs = readResource("/web/hljs/highlight.min.js");
        this.hlThemeLight = readResource("/web/hljs/styles/github.min.css");
        this.hlThemeDark = readResource("/web/hljs/styles/github-dark.min.css");
    }

    /**
     * @param bodyHtml  HTML fragment of the content
     * @param theme     current theme
     * @param fontScale font zoom factor (1.0 = 100%)
     * @return complete HTML document
     */
    public String build(String bodyHtml, Theme theme, double fontScale) {
        String themeClass = theme == Theme.DARK ? "theme-dark" : "theme-light";
        String hlTheme = theme == Theme.DARK ? hlThemeDark : hlThemeLight;
        long fontPercent = Math.round(fontScale * 100);
        String body = emojiRenderer.render(bodyHtml);

        return """
                <!DOCTYPE html>
                <html lang="en" class="%s">
                <head>
                    <meta charset="UTF-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                    <style>%s</style>
                    <style>%s</style>
                    <style>:root { font-size: %d%%; }</style>
                </head>
                <body>
                    <article class="markdown-body">
                        %s
                    </article>
                    <script>%s</script>
                    <script>
                        document.addEventListener('DOMContentLoaded', function () {
                            if (window.hljs) {
                                document.querySelectorAll('pre code').forEach(function (block) {
                                    try { hljs.highlightElement(block); } catch (e) {}
                                });
                            }
                        });
                    </script>
                </body>
                </html>
                """.formatted(themeClass, hlTheme, baseCss, fontPercent, body, hljsJs);
    }

    private static String readResource(String path) {
        try (InputStream in = HtmlPageBuilder.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IllegalStateException("Resource not found on classpath: " + path);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to read resource: " + path, e);
        }
    }
}
